version: '3'

services:
  web:
    container_name: web
    image: ghcr.io/swuecho/chat_frontend:latest # or use tag for better stability, e.g. v0.0.3
    ports:
      - 8080:80
    depends_on:
      - api
      - db
  api:
    container_name: api
    image: ghcr.io/swuecho/chat_backend:latest # or use tag for better stability, e.g.v0.0.3
    expose:
      - 8077
    ports:
      - 8077:8077
    environment:
      - OPENAI_API_KEY=thisisakey
      # api call in 10min
      # set this to zero if your server is in public network. only increase ratelimit in admin panel for trusted users.
      - OPENAI_RATELIMIT=100
      - CLAUDE_API_KEY=thisisclaudekey # do not change if you do not have claude api key
      - PG_HOST=db
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASS=thisisapassword
      - PG_PORT=5432
      # JWT_SECRET is the key used to encrypt/decrypt the JWT token
      # !!! change this, with output of: openssl rand -base64 32
      - JWT_SECRET='RqJrJBINOsL6PVSocqVfVk8a8H9u4juq55YN6PvnlPE='
      # JWT_AUD represents the audience of the JWT token, i.e., the recipient or target
      - JWT_AUD=bc442bb2b1d848fba5be2aa24123e711
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "thisisapassword"
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
